[theme]
# Primary accent color for interactive elements.
primaryColor = "#A4B1E3"

# Background color for the main content area.
backgroundColor = "#000435"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#A4B1E3"

# Color used for almost all text.
textColor = "#FFFFFF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
